### ISSUE TITLE
Using position>horizontal>position>middle shifts dismiss button to next line

### ISSUE THREAD

**Issue by nbjgi1** [dominique-mueller/angular-notifier#149]
I don't get the same issue when using position:left for example.

**Comment by dcrouch79** [comment]
As a workaround the wrapping can be disabled in `styles.css`:

```css
notifier-notification{
  white-space: nowrap;
}
````
